name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: visitcount

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build SenderExample
      run: g++ -Wall -Wextra -Werror --coverage -o SenderExe Sender/Sender.cpp
      
    - name: build ReceiverExample
      run: g++ -Wall -Wextra -Werror --coverage -o ReceiverExe Receiver/Receiver.cpp
      
    - name: static analysis
      run: cppcheck --enable=all --error-exitcode=1 .
      
    - name: run
      run: ./SenderExe | ./ReceiverExe
    
    - name: coverage report
      run: gcov -r *.cpp
