name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build Sender
      run: g++ -Wall -Wextra -Werror -fprofile-arcs -ftest-coverage -o SenderExe Sender/*.cpp
      
    - name: build Receiver
      run: g++ -Wall -Wextra -Werror -fprofile-arcs -ftest-coverage -o ReceiverExe Receiver/*.cpp
      
    - name: static analysis
      run: cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=1 -iReceiver-Test/ReceiverTest.cpp -iSender-Test/SenderTest.cpp -iSenderExtFun-Test/SenderExtTest.cpp .
      
    - name: run main functionality
      run: ./SenderExe | ./ReceiverExe
    
    - name: coverage report Sender
      run: gcov -b -c Sender.cpp 
      
    - name: coverage report Receiver
      run: gcov -b -c Receiver.cpp
      
    - name: build Sender-Test
      run: g++ -Wall -Wextra -Werror -fprofile-arcs -ftest-coverage -o SenderTestExe Sender-Test/SenderTest.cpp Sender/SenderFunctions.cpp
    
    - name: build Receiver-Test
      run: g++ -Wall -Wextra -Werror -fprofile-arcs -ftest-coverage -o ReceiverTestExe Receiver-Test/ReceiverTest.cpp Receiver/Receiver.cpp
    
    - name: run Sender-Test
      run: ./SenderTestExe
    
    - name: run Receiver-Test
      run: ./ReceiverTestExe
    
    - name: coverage report Sender-Test
      run: gcov -b -c SenderTestFunctions.cpp
    
    - name: coverage report Receiver-Test
      run: gcov -b -c ReceiverTestFunctions.cpp
    
    - name: build Sender with extended functionality
      run: g++ -Wall -Wextra -Werror -fprofile-arcs -ftest-coverage -o SenderExtFuncExe SenderExtendedFunc/SenderExtFunc.cpp
    
    - name: run extended functionality
      run: ./SenderExtFuncExe | ./ReceiverExe
      
    - name: build Sender-Test with extended functionality
      run: g++ -Wall -Wextra -Werror -fprofile-arcs -ftest-coverage -o SenderExtTestExe SenderExtFun-Test/*.cpp
    
    - name: run Sender Extended Functionality-Test
      run: ./SenderExtTestExe
    
    - name: coverage report Sender Extended Functionality-Test
      run: gcov -b -c SenderExtFunctions.cpp
    
    - name: coverage report Sender Extended Functionality
      run: gcov -b -c SenderExtFunc.cpp
